CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE oauth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    subject_hmac VARCHAR(64) NOT NULL,
    connected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_oauth_identities_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT uk_oauth_identities_provider_subject UNIQUE (provider, subject_hmac),
    CONSTRAINT uk_oauth_identities_member_provider UNIQUE (member_id, provider)
);

CREATE TABLE member_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    nickname VARCHAR(20) NOT NULL,
    muted BOOLEAN NOT NULL,
    master_volume INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_member_settings_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT uk_member_settings_member UNIQUE (member_id),
    CONSTRAINT uk_member_settings_nickname UNIQUE (nickname),
    CONSTRAINT ck_member_settings_master_volume CHECK (master_volume BETWEEN 0 AND 100)
);

CREATE TABLE skills (
    id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL,
    configuration JSONB NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE items (
    id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL,
    item_type VARCHAR(20) NOT NULL,
    max_level INTEGER NOT NULL,
    configuration JSONB NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT ck_items_max_level CHECK (max_level >= 1)
);

CREATE TABLE characters (
    id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL,
    skill_id VARCHAR(64) NOT NULL,
    starting_item_id VARCHAR(64) NOT NULL,
    unlocked_by_default BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT fk_characters_skill FOREIGN KEY (skill_id) REFERENCES skills (id),
    CONSTRAINT fk_characters_starting_item FOREIGN KEY (starting_item_id) REFERENCES items (id)
);

CREATE TABLE item_evolution_recipes (
    id VARCHAR(64) PRIMARY KEY,
    display_name VARCHAR(80) NOT NULL,
    first_item_id VARCHAR(64) NOT NULL,
    second_item_id VARCHAR(64) NOT NULL,
    configuration JSONB NOT NULL,
    enabled BOOLEAN NOT NULL,
    CONSTRAINT fk_evolution_first_item FOREIGN KEY (first_item_id) REFERENCES items (id),
    CONSTRAINT fk_evolution_second_item FOREIGN KEY (second_item_id) REFERENCES items (id),
    CONSTRAINT uk_evolution_materials UNIQUE (first_item_id, second_item_id),
    CONSTRAINT ck_evolution_distinct_materials CHECK (first_item_id <> second_item_id)
);

CREATE TABLE member_characters (
    member_id BIGINT NOT NULL,
    character_id VARCHAR(64) NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (member_id, character_id),
    CONSTRAINT fk_member_characters_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_member_characters_character FOREIGN KEY (character_id) REFERENCES characters (id)
);

CREATE TABLE member_items (
    member_id BIGINT NOT NULL,
    item_id VARCHAR(64) NOT NULL,
    unlocked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (member_id, item_id),
    CONSTRAINT fk_member_items_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_member_items_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE play_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_session UUID NOT NULL,
    member_id BIGINT NOT NULL,
    character_id VARCHAR(64) NOT NULL,
    score BIGINT NOT NULL,
    kill_count INTEGER NOT NULL,
    level INTEGER NOT NULL,
    outcome VARCHAR(20) NOT NULL,
    duration_millis BIGINT NOT NULL,
    final_build JSONB NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ranking_eligible BOOLEAN NOT NULL,
    CONSTRAINT fk_play_records_member FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_play_records_character FOREIGN KEY (character_id) REFERENCES characters (id),
    CONSTRAINT uk_play_records_game_session UNIQUE (game_session),
    CONSTRAINT ck_play_records_score CHECK (score >= 0),
    CONSTRAINT ck_play_records_kill_count CHECK (kill_count >= 0),
    CONSTRAINT ck_play_records_level CHECK (level >= 1),
    CONSTRAINT ck_play_records_duration CHECK (duration_millis >= 0)
);

CREATE INDEX ix_play_records_member_ended
    ON play_records (member_id, ended_at DESC);

CREATE INDEX ix_play_records_ranking_score
    ON play_records (ranking_eligible, score DESC, ended_at ASC);

CREATE TABLE outbox_events (
    id VARCHAR(36) PRIMARY KEY,
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id VARCHAR(80) NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE INDEX ix_outbox_events_status_occurred
    ON outbox_events (status, occurred_at);

INSERT INTO skills (id, display_name, description, configuration, enabled) VALUES
    ('protective-barrier', '호신결계', '한 판에 한 번 충돌을 막고 잠시 무적이 된다.', '{}', TRUE),
    ('gale-step', '질풍걸음', '이동 속도가 25% 증가한다.', '{}', TRUE);

INSERT INTO items (id, display_name, description, item_type, max_level, configuration, enabled) VALUES
    ('seal-talisman', '봉인 부적', '가장 가까운 적에게 부적을 발사한다.', 'WEAPON', 5, '{}', TRUE),
    ('flame-fan', '화염 부채', '전방에 불꽃 부채를 펼친다.', 'WEAPON', 5, '{}', TRUE),
    ('exorcist-sword', '벽사검', '주변을 베어 악귀를 물리친다.', 'WEAPON', 5, '{}', TRUE),
    ('returning-boomerang', '회귀 부메랑', '되돌아오는 투사체를 던진다.', 'WEAPON', 5, '{}', TRUE),
    ('thunder-bell', '낙뢰 방울', '적의 위치에 번개를 내린다.', 'WEAPON', 5, '{}', TRUE),
    ('spirit-gourd', '혼령 호리병', '주변 혼령을 끌어당겨 공격한다.', 'WEAPON', 5, '{}', TRUE);

INSERT INTO characters (
    id, display_name, description, skill_id, starting_item_id, unlocked_by_default, enabled
) VALUES
    ('dokkaebi-hunter', '도깨비 사냥꾼', '봉인 부적과 호신결계로 싸운다.',
     'protective-barrier', 'seal-talisman', TRUE, TRUE),
    ('gale-shaman', '질풍 무녀', '화염 부채와 질풍걸음으로 싸운다.',
     'gale-step', 'flame-fan', FALSE, TRUE);

INSERT INTO item_evolution_recipes (
    id, display_name, first_item_id, second_item_id, configuration, enabled
) VALUES
    ('ten-thousand-seal-array', '만방봉인진', 'seal-talisman', 'exorcist-sword', '{}', TRUE),
    ('heavenly-thunder-seal', '천뢰봉인부', 'seal-talisman', 'thunder-bell', '{}', TRUE),
    ('inferno-returning-wheel', '업화회륜', 'flame-fan', 'returning-boomerang', '{}', TRUE),
    ('blue-flame-spirit-gourd', '청염귀호', 'flame-fan', 'spirit-gourd', '{}', TRUE),
    ('lunar-eclipse-twin-blades', '월식쌍인', 'exorcist-sword', 'returning-boomerang', '{}', TRUE),
    ('thunder-flame-divine-orb', '뇌화신주', 'thunder-bell', 'spirit-gourd', '{}', TRUE);
