package kr.joseonnight.desktop.gameplay;

/** Stable sound cue values received from the game-core protocol. */
public enum SoundCue {
    LEVEL_UP,
    GUARD,
    CHEST_OPENED,
    DEFEAT,
    SEAL_TALISMAN_ATTACK,
    FLAME_FAN_ATTACK,
    EXORCIST_SWORD_ATTACK,
    RETURNING_BOOMERANG_ATTACK,
    THUNDER_BELL_ATTACK,
    SPIRIT_GOURD_ATTACK,
    TEN_THOUSAND_SEAL_ARRAY_ATTACK,
    HEAVENLY_THUNDER_SEAL_ATTACK,
    INFERNO_RETURNING_WHEEL_ATTACK,
    BLUE_FLAME_SPIRIT_GOURD_ATTACK,
    LUNAR_ECLIPSE_TWIN_BLADES_ATTACK,
    THUNDER_FLAME_DIVINE_ORB_ATTACK
}
